// Static type data for all 151 Gen 1 Pokémon
export const POKEMON_TYPES = {
  bulbasaur: ['grass', 'poison'],
  ivysaur: ['grass', 'poison'],
  venusaur: ['grass', 'poison'],
  charmander: ['fire'],
  charmeleon: ['fire'],
  charizard: ['fire', 'flying'],
  squirtle: ['water'],
  wartortle: ['water'],
  blastoise: ['water'],
  caterpie: ['bug'],
  metapod: ['bug'],
  butterfree: ['bug', 'flying'],
  weedle: ['bug', 'poison'],
  kakuna: ['bug', 'poison'],
  beedrill: ['bug', 'poison'],
  pidgey: ['normal', 'flying'],
  pidgeotto: ['normal', 'flying'],
  pidgeot: ['normal', 'flying'],
  rattata: ['normal'],
  raticate: ['normal'],
  spearow: ['normal', 'flying'],
  fearow: ['normal', 'flying'],
  ekans: ['poison'],
  arbok: ['poison'],
  pikachu: ['electric'],
  raichu: ['electric'],
  sandshrew: ['ground'],
  sandslash: ['ground'],
  'nidoran-f': ['poison'],
  nidorina: ['poison'],
  nidoqueen: ['poison', 'ground'],
  'nidoran-m': ['poison'],
  nidorino: ['poison'],
  nidoking: ['poison', 'ground'],
  clefairy: ['fairy'],
  clefable: ['fairy'],
  vulpix: ['fire'],
  ninetales: ['fire'],
  jigglypuff: ['normal', 'fairy'],
  wigglytuff: ['normal', 'fairy'],
  zubat: ['poison', 'flying'],
  golbat: ['poison', 'flying'],
  oddish: ['grass', 'poison'],
  gloom: ['grass', 'poison'],
  vileplume: ['grass', 'poison'],
  paras: ['bug', 'grass'],
  parasect: ['bug', 'grass'],
  venonat: ['bug', 'poison'],
  venomoth: ['bug', 'poison'],
  diglett: ['ground'],
  dugtrio: ['ground'],
  meowth: ['normal'],
  persian: ['normal'],
  psyduck: ['water'],
  golduck: ['water'],
  mankey: ['fighting'],
  primeape: ['fighting'],
  growlithe: ['fire'],
  arcanine: ['fire'],
  poliwag: ['water'],
  poliwhirl: ['water'],
  poliwrath: ['water', 'fighting'],
  abra: ['psychic'],
  kadabra: ['psychic'],
  alakazam: ['psychic'],
  machop: ['fighting'],
  machoke: ['fighting'],
  machamp: ['fighting'],
  bellsprout: ['grass', 'poison'],
  weepinbell: ['grass', 'poison'],
  victreebel: ['grass', 'poison'],
  tentacool: ['water', 'poison'],
  tentacruel: ['water', 'poison'],
  geodude: ['rock', 'ground'],
  graveler: ['rock', 'ground'],
  golem: ['rock', 'ground'],
  ponyta: ['fire'],
  rapidash: ['fire'],
  slowpoke: ['water', 'psychic'],
  slowbro: ['water', 'psychic'],
  magnemite: ['electric', 'steel'],
  magneton: ['electric', 'steel'],
  "farfetch'd": ['normal', 'flying'],
  doduo: ['normal', 'flying'],
  dodrio: ['normal', 'flying'],
  seel: ['water'],
  dewgong: ['water', 'ice'],
  grimer: ['poison'],
  muk: ['poison'],
  shellder: ['water'],
  cloyster: ['water', 'ice'],
  gastly: ['ghost', 'poison'],
  haunter: ['ghost', 'poison'],
  gengar: ['ghost', 'poison'],
  onix: ['rock', 'ground'],
  drowzee: ['psychic'],
  hypno: ['psychic'],
  krabby: ['water'],
  kingler: ['water'],
  voltorb: ['electric'],
  electrode: ['electric'],
  exeggcute: ['grass', 'psychic'],
  exeggutor: ['grass', 'psychic'],
  cubone: ['ground'],
  marowak: ['ground'],
  hitmonlee: ['fighting'],
  hitmonchan: ['fighting'],
  lickitung: ['normal'],
  koffing: ['poison'],
  weezing: ['poison'],
  rhyhorn: ['ground', 'rock'],
  rhydon: ['ground', 'rock'],
  chansey: ['normal'],
  tangela: ['grass'],
  kangaskhan: ['normal'],
  horsea: ['water'],
  seadra: ['water'],
  goldeen: ['water'],
  seaking: ['water'],
  staryu: ['water'],
  starmie: ['water', 'psychic'],
  'mr-mime': ['psychic', 'fairy'],
  scyther: ['bug', 'flying'],
  jynx: ['ice', 'psychic'],
  electabuzz: ['electric'],
  magmar: ['fire'],
  pinsir: ['bug'],
  tauros: ['normal'],
  magikarp: ['water'],
  gyarados: ['water', 'flying'],
  lapras: ['water', 'ice'],
  ditto: ['normal'],
  eevee: ['normal'],
  vaporeon: ['water'],
  jolteon: ['electric'],
  flareon: ['fire'],
  porygon: ['normal'],
  omanyte: ['rock', 'water'],
  omastar: ['rock', 'water'],
  kabuto: ['rock', 'water'],
  kabutops: ['rock', 'water'],
  aerodactyl: ['rock', 'flying'],
  snorlax: ['normal'],
  articuno: ['ice', 'flying'],
  zapdos: ['electric', 'flying'],
  moltres: ['fire', 'flying'],
  dratini: ['dragon'],
  dragonair: ['dragon'],
  dragonite: ['dragon', 'flying'],
  mewtwo: ['psychic'],
  mew: ['psychic'],
};

export const TYPE_COLORS = {
  normal: { id: 1, bg: 'bg-gray-400', text: 'text-white' },
  fighting: { id: 2, bg: 'bg-red-700', text: 'text-white' },
  flying: { id: 3, bg: 'bg-indigo-300', text: 'text-gray-900' },
  poison: { id: 4, bg: 'bg-purple-500', text: 'text-white' },
  ground: { id: 5, bg: 'bg-yellow-600', text: 'text-white' },
  rock: { id: 6, bg: 'bg-yellow-700', text: 'text-white' },
  bug: { id: 7, bg: 'bg-lime-500', text: 'text-white' },
  ghost: { id: 8, bg: 'bg-purple-800', text: 'text-white' },
  steel: { id: 9, bg: 'bg-slate-400', text: 'text-white' },
  fire: { id: 10, bg: 'bg-orange-500', text: 'text-white' },
  water: { id: 11, bg: 'bg-blue-500', text: 'text-white' },
  grass: { id: 12, bg: 'bg-green-500', text: 'text-white' },
  electric: { id: 13, bg: 'bg-yellow-400', text: 'text-gray-900' },
  psychic: { id: 14, bg: 'bg-pink-500', text: 'text-white' },
  ice: { id: 15, bg: 'bg-cyan-300', text: 'text-gray-900' },
  dragon: { id: 16, bg: 'bg-indigo-700', text: 'text-white' },
  dark: { id: 17, bg: 'bg-gray-800', text: 'text-white' },
  fairy: { id: 18, bg: 'bg-pink-300', text: 'text-gray-900' },
};

export const ALL_TYPES = Object.keys(TYPE_COLORS);
